# Generated by Django 3.2.10 on 2022-02-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dev_A', '0002_auto_20220207_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
